language: "node_js"
deploy:
  provider: s3
  access_key_id: "AKIAJRM4OWDCP4AQ7IKA"
  secret_access_key:
    secure: UacO+cErKrlL8MqieRNQu23lEUudq5Jw8p9w+dLsLdx+jhj6a42zttebzgc32OFYxvkmjbFWhDW1A6SBgYpR7ZkS4WnpEd9KDEGt42fBn6ZUXChkrCBPlZh5C9MZ5Knyp4WYOUuBez8gb+FHAyCY41jv6hOnGHxvQDY+TRBHeCuB4cewYuXLeJlCxGMvLTIWx+miR8Hqr82X2fhzwMahkeDi7FC42h0Md8R9TNXLCmuinKFQfslTOwvh/qeM7AZYq5S9te+oaiylfq1oZ+oBJPoIUp/BxelxyfQVFcKxWGV4KlKCFE0UjZrr6FwPFYBbjHjklY1UOCCNd4f5LAaBADG8X3HZDy0dOwTtz+VBhdgXSm2LxWpDbtnAEP4rJDtWSuZOVfdL1s/cAGVo4oqGnwpNFUdgUH3n6RYgoZEKH3AoMtDbu8pU0VcgEPQhCXMifXEFe8ZaZT7gKVXDwklGtGlu9YxX+J/yKupmp0vghYZkLFosAzYsJYB+MeIqCjVbcej6w1TH676dQKmWmyYk7uaw2/8ft2i7T5SYnYJBXM+RoiV6yAbh/WXBZbD/B8RAvFgwOsXJdZ3fwsPXN+hdFTQKYbDdQ8Q2abbAm/BP+gIaLtjhyqwIVd6i6Jqaxms4Byf6aWhdHtvezvRzILmFpXqBvVtxuOTLmP8nhoBAlFg=
  bucket: "network-pulse-staging"